name: CI/CD

env:
    BUNDLEWATCH_GITHUB_TOKEN: "123"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  yarn:
    uses: ./.github/workflows/yarn-cache.yml

  lint:
    needs: yarn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - run: yarn lint

  build:
    needs: yarn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: |
            if [ -z "${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}" ]; then
              echo "Secret is NOT set."
            else
              echo "Secret is set."
            fi
      - run: echo ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
      - run: yarn build
      - run: npx bundlewatch dist/assets/*




